apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: gitops-lab
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: ghcr.io/jhlee95129/gitops-lab-api:latest
          ports:
            - containerPort: 4000
          env:
            - name: APP_VERSION
              value: "0.1.0"
